const express = require("express");
const bodyParser = require('body-parser');
const nodemailer = require('nodemailer');
const app = express();


app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
const route = express.Router();
const port = process.env.PORT || 5000;
app.use('/v1', route);
app.use('/sendEmail',sendEmail);
app.listen(port, () => {
    console.log(`Server listening on port ${port}`);
}); 



function sendEmail(req,res){
let transporter = nodemailer.createTransport({
   host : 'smtp.mailtrap.io',
 
     auth: {
       user: "061f505505d734", // generated by Mailtrap
       pass: "79ed52192069ca" // generated by Mailtrap
     }
   });


const mailOptions = {
    from: "handsOnHongKong@gmail.com", //Adding sender's email
    to: req.query.dest, //Getting recipient's email by query string
    subject: 'Email Sent via Firebase', //Email subject
    html: `<p>
    Hi <span>${req.query.volunteerName}</span>!
  </p>
  <br>
  <p>
   “You cannot do a kindness too soon, for you never know how soon it will be too late.”
    ― Ralph Waldo Emerson
  </p>
  <p>
    We who are privileged enough to have comfortable lives should help those who have been dealt a bad hand by life.
    <span>${req.query.ngoName}</span> is organizing <span>${req.query.eventName}</span> on <span>${req.query.dateAndTime}</span>. The event will take place at <span>${req.query.location}</span>.
  </p>
  <p>
    We at HandsOn Hong Kong believe that it is a priceless opportunity for you to give back to the Community.
    We aspire for a Hong Kong that where our community serves together to meet all social needs, and we are excited to have you as a part of our journey
  </p>
  <br>
  <p>
    Regards,<br>
    HandsOn Hong Kong
  </p>` //Email content in HTML
};

transporter.sendMail(mailOptions, function (err, info) {
    if(err)
      req.send(err.toString())
    else
      res.send("success");
 });
}